### ISSUE TITLE
Incorrect return type-hint in jcchavezs/zipkin-opentracing 0.2

### ISSUE THREAD

**Issue by Rainrider** [auxmoney/OpentracingBundle-Zipkin#21]
`jcchavezs/zipkin-opentracing` had an incorrect return type-hint which leads to a TypeError rendering this bundle unusable. This was resolved in https://github.com/jcchavezs/zipkin-php-opentracing/pull/49. They pushed a [version 1.0.0](https://github.com/jcchavezs/zipkin-php-opentracing/releases/tag/1.0.0) which has the fix in place. However this version uses `opentracing/opentracing` 1.0.1 with which your bundle is incompatible because of how dependencies are handled.

@cawolf mentioned in https://github.com/auxmoney/OpentracingBundle-core/issues/53 that https://github.com/jukylin/jaeger-php/issues/95 is a blocker for this. However this project has not released since May 28, 2020 despite them even having a [pending PR](https://github.com/jukylin/jaeger-php/pull/100) for it. Would you consider leaving the JaegerBundle as is until they sort it out and update core and other bundles to opentracing 1.0?

**Comment by cawolf** [comment]
Hi @Rainrider ,

thank you for raising this issue. We understand the problem and were thinking about forking the original vendor for some time now, for the exact same reason you mentioned. Your issue is now the reason to actually do so.

Our reasoning for this step is, that if we would drop the jaeger-php vendor, we would lose all our functional tests for most of our plugins, and we are not very happy to do so. Instead, we will be fixing and finalizing the `dev_v3` branch, which is nearly complete, and release it soon as `auxmoney/jaeger-php`. We will then migrate our functional tests in all plugins and the `auxmoney/OpentracingBundle-Jaeger` plugin itself to our vendor, updating to opentracing 1.0.1 in the process.
